"""Package Waverider's SHARC objects for `dnfw.waverider.dsp` (Milestone 5).

    python scripts/gen_waverider_sharc.py [--assemble]

`dnfw.waverider.dsp` applies committed objects, never an assembler, so the mod runs
anywhere. This writes `src/dnfw/waverider/sharc_code.json` from:

- `csrc/waverider/sharc/reader_m9.json` and `machine9_live.json` (Milestone 9a: M5's
  reader and loop with osc 1's level as a gain; the M5 sources stay beside them) --
  each (re)written from its `.asm` with selas when `--assemble` (WSL + selache). The
  spec keeps M5's key names, `reader` and `machine5_live`, which `dsp` reads;
- the entry `JUMP 0x180200;`, one selas-assembled instruction (`--assemble`), or
  the previous `sharc_code.json`'s copy.

Each object carries its source's sha256 (LF-normalised), and without `--assemble` a
source that no longer matches its committed object is refused, as the Milestone 3/4
gates do. selache (GPL-3.0) is a tool here; nothing of it is copied.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import pathlib
import sys
import tempfile

ROOT = pathlib.Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "src"))
sys.path.insert(0, str(ROOT / "scripts"))

from dnfw.waverider import dsp  # noqa: E402

SHARC = ROOT / "csrc" / "waverider" / "sharc"
TOOLCHAIN = "selache selas -proc ADSP-21569 (js216/selache 2b26d3b, GPL-3.0, WSL)"
ENTRY_LINE = f"JUMP {dsp.COUNT_SW:#x};"           # the block counter, which goes on to the loop
IDLE_LINE = f"JUMP {dsp.IDLE_SW:#x};"
EMARK_LINE = f"JUMP {dsp.EMARK_SW:#x};"


def sha(path: pathlib.Path) -> str:
    return hashlib.sha256(path.read_bytes().replace(b"\r\n", b"\n")).hexdigest()


def committed(name: str) -> dict:
    src, obj = SHARC / f"{name}.asm", SHARC / f"{name}.json"
    spec = json.loads(obj.read_text(encoding="utf-8"))
    if spec["source_sha256"] != sha(src):
        raise SystemExit(f"{obj.name} is stale for {src.name}: rerun with --assemble")
    return spec


def assemble(name: str, load_sw: int, work: pathlib.Path) -> dict:
    import sharc_waverider_m3 as m3  # noqa: PLC0415  (needs WSL only when assembling)
    src = SHARC / f"{name}.asm"
    be, offsets = m3._selas(src, work)
    spec = {"source": src.relative_to(ROOT).as_posix(), "source_sha256": sha(src),
            "toolchain": TOOLCHAIN, "section": "seg_pmco", "load_sw": hex(load_sw),
            "object_parcels_be": be.hex(), "instruction_offsets": offsets}
    (SHARC / f"{name}.json").write_text(json.dumps(spec, indent=2) + "\n", encoding="utf-8",
                                        newline="\n")
    return spec


def one_jump(line: str, at_sw: int, work: pathlib.Path) -> dict:
    import sharc_waverider_m3 as m3  # noqa: PLC0415
    be, _ = m3._selas_line(line, work)
    return {"source": line, "toolchain": TOOLCHAIN, "at_sw": hex(at_sw), "object_parcels_be": be.hex()}


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--assemble", action="store_true")
    a = ap.parse_args(argv)
    old = json.loads(dsp.CODE.read_text(encoding="utf-8")) if dsp.CODE.exists() else {}
    with tempfile.TemporaryDirectory() as tmp:
        work = pathlib.Path(tmp)
        if a.assemble:
            reader = assemble("reader_m9", dsp.READER_SW, work)
            loop = assemble("machine9_live", dsp.LOOP_SW, work)
            idle = assemble("idle_load", dsp.IDLE_SW, work)
            count = assemble("block_count", dsp.COUNT_SW, work)
            emark = assemble("entry_mark", dsp.EMARK_SW, work)
            ejump = one_jump(EMARK_LINE, dsp.CALL_SITE_SW, work)
            jump = one_jump(ENTRY_LINE, dsp.ENTRY_SW, work)
            ijump = one_jump(IDLE_LINE, dsp.IDLE_SITE_SW, work)
        else:
            reader = committed("reader_m9")
            loop = committed("machine9_live")
            idle = committed("idle_load")
            count = committed("block_count")
            emark = committed("entry_mark")
            ejump = old["emark_jump"]
            if "entry_jump" not in old or "idle_jump" not in old:
                raise SystemExit("no entry or idle JUMP committed yet: run with --assemble")
            jump, ijump = old["entry_jump"], old["idle_jump"]
    spec = {"note": "generated by scripts/gen_waverider_sharc.py; do not edit",
            "reader": {k: v for k, v in reader.items() if k != "instruction_offsets"},
            "machine5_live": {k: v for k, v in loop.items() if k != "instruction_offsets"},
            "entry_jump": jump,
            "idle_load": {k: v for k, v in idle.items() if k != "instruction_offsets"},
            "idle_jump": ijump,
            "block_count": {k: v for k, v in count.items() if k != "instruction_offsets"},
            "entry_mark": {k: v for k, v in emark.items() if k != "instruction_offsets"},
            "emark_jump": ejump}
    dsp.CODE.write_text(json.dumps(spec, indent=2) + "\n", encoding="utf-8", newline="\n")
    print(f"wrote {dsp.CODE.relative_to(ROOT)}: reader {len(reader['object_parcels_be']) // 2} B, "
          f"loop {len(loop['object_parcels_be']) // 2} B, entry {len(jump['object_parcels_be']) // 2} B")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
